[tool.black]
line-length = 88

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    "ignore:websockets.legacy is deprecated:DeprecationWarning:websockets.legacy:6"
]
markers = [
    "asyncio: mark a test as asynchronous (for pytest-asyncio)",
]